sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product testn-047
env:
  global:
    -
      # LTD_AWS_ID
      secure: c9NE4G+lAHUVHaII1aYO3MNU1/N/J1O3aVXszX8IRQw+p61k4Wf4qFziyHaVQ5ebrSWCdXcE8K0kgeVBMzTWs2GxXNFOKfvXSCZpDu7kepSwHR+cUe6UlidrA/B2br6bD/ROZ8TCAwvFXQwz+DRKSNu/+MEyh2nlf4stJunsD+zJXDnNVczbebip+AMnwpaBUYBEdWagbcVCyF9V0som9Y5xmNxnzQHDQvTZMMm0YvKrAUvKjnygVRzYe/RC13uajo/hyPvHoPzIwr8fac4n+69fiJ7cl3YFL0YLgXuPqEHt4Lrbten0nKLJ25D/sNdUQEOdeU2QYKfk46JOR+Ar2d0OfkHhguBMl90Y1MgT2AfxiHLdjcB+Z2uqmym5Sust9t/0fwpvURCoNcDkj+zNucRoCT0LqMjdYw0YQH1yAWKqYIPV6swlQ6Y/gf0W76HnFLOJBgThG9ctPkdCVa9wBd3NKkDw3nBMKvdCS826AxDx1Y87Ewg0ih6YvrBXA9A3rAA2FRm6ktmHnRX4URDdp/jvuxgMiOfXKi67Jrh1rA81X5euljbSRF6THpAa4bqxTFDNFlj5CSCRP5ISMTCt6znb0ptwStfvlDh88OF+K5GH3WY8XizCjUBljz6XAahQX4FW+NfVLXSGkJ0K39ti1OHhptFXiX9c+2azh92R35Q=
    -
      # LTD_AWS_SECRET
      secure: aeoxPbVM1nSdYGPklLakWm1sWtJNARDBoAUDpDY+dqSRBSbpu7UCDxXlk43NloD/oPdl6r3hHcnszrHXgnS4Y1/orzu1q4EnUvfdPqg/xbYZRxCvrL6oNcIy1tqRx01MRvfMfAmlpn3HoWgyAOum4aKDrrHNaviCtEfG6uHJz8FixJvLO+VHgL3d5acbdIsljw/4BIY1sFoOrn3NHYAgJHk0x2d0BMg+QL7zUWJlId3Rtw8Cq1zvuGftIbCFBAdx7frbhAfkuKwE5JtyAU9cIJ+/RmT+eO9RBeaBJW/Zq276hQQOgHG4luoHjVr+RqHbT3xuQmLPUXYYQ0ONucDAkzN5/AAximQg2ZxSOTlQ95WzhkwZt1fanSbzwkNrylpHF04l+ndWpbvc7aoUSrXnOkjZIWgSIcc5uuZoCZKT/2XQRZVxM9665il6JSTytHcQv3yhzqhB4Wx3451Ooyn5Dj8IkfTGJ4VMezczd5Bxlkpwi9+S1H6hD+4S9KeG9bLRjdc4a9fXaAtiL2ADM7MaVYC6PCgycmNiWnxMxv1LK6nqT+LDXOrx2hjU9SaMyFS1BpEYO+JX8wCoTA5pojRgPhvTTyeS+L9OGz85t9ipgShRE/3O9OPweMXIx27bfyrDnBybpKl+KAGtMa/C3CBaoIZ0XaJTaRdb5xgymou2C70=
    -
      # LTD_USERNAME
      secure: HmCIdEfEiOFVnv43v4OZ+KD2e9wcbkv6Z7vhtWfI7tAWfvhEh5Xvizy0PORlenAAs3p7FsR6lZpH+qA6ZFMkR3Ws189Hr6TO3Ph97TnIcBKF2UeAupYSCG5q+irxwhhKztiEoAHIOIO90tAyWmnxeoT3N4r/59P+CoXYS8vgf0RpcSoFsMPrng5O61Yxiuj7CBbm72jS73lAOIoFP8Mbv+HMxkm+saaXSJiaGUyGiCdxq5sI2SbOFy1i1GiAowjcSH/yKLTBXqsJc/97ESrJhGXsSC3+dd7T06lknmYswY5I9v7v+GKEgP1sTWJ9gEobPMWMNo1vB1wKiBxG9chSquXU1yGVjfVxjvui7NUHUFUQNkfdCtx5YM5w9ZQSllwRhCYVLE/bRGPVAa086BvyuvV2yG7IeTNj8DZqbxhSkXYdlPY+T1a0l92Y16SrZizbAFsanK2FKZ0FQ2vazi49AMO7epSk8Lev5FjOLCZHh3yFGlBwc5JvLfjVc15Nqtf7l3XDIG3mp/MTgYR0HI5iAkxOOn10hXoEq57QDb2tGeSY5Djlz6y3BAPMI8sfvuTg68F1zNtBauUU2JXuACcxT0779x22dUja0z6DAZ1zondkwbxxSYmtpnhl8Ma5v+l+ohs+EZVuQn7xB61E9SY2ygogJ5idZx5G4gSXRxW3ng4=
    -
      # LTD_PASSWORD
      secure: BWyJZgj8dKbdOlrWEU06xPsBI6YUo7WyyKPVwgCKB9Bni3NnIshvO46B5NTYLFMna3ECDX/rUmFonwdeY8a9+N29EG9UwW0aLFwVGyelmlWPTo0RR88BhUhyasMYDE51cEQuo7nFmMxoYBC58cwJDowohlozP7uz7dnEb9Vi27gjyn0kn2QblhxKAWHlQfUvxE2FFL9Xl3w1mlhQSf/6K0nBe3mHSr5dCsMALYwINxYiSH9phUXOggDtMomNt7IPurGTLJmpYHeU3R0k0QSz7NO9/iXWefLtAi/7YU2LR7VOStY+lujeiUiiHe7+YKpEEv+JAux2Cyyvbym/H3RURlH3coLW/TcaQ868gkEzu/4HRBsibYBashh/V2dwwxHlhcZvmxgKAjHkGfvev/gX9omQMKxcmNLIAVa0Ioy1CUAAUcF+fL2nudNqVLMBeO+wf02dIqnYoY9Mt1679ym3ueQxR+edzJ3qXTBgLFTUssZ/Qxa47T7XHVy7BNgW5chU8ZHC5MyffTVd6hN43kp3BJtVqmL7ePmyeuesl+bcra9iH42eQJTkNa8iqFpe8Dkz1mHHBpG3sydA9T979fb6+NKaGoOBcQqy99zr041+dJbf8ak1OX34Zph+5uZZJ2PgEcRPGOLUDDlcX+82rcsTRzWKCAxk3g27s6a9HWqDCgg=
